###
# POST /users
###
POST http://localhost:3333/users
Content-Type: application/json

{
    # "id_user": 1,
    "complete_name_user": "",
    "cpf_user": "sdf",
    "email_user": "",
    "password_user": "441133",
    "confirm_password_user": "",
    "premium_user": false
}

###
# GET /users 
###
GET http://localhost:3333/users
